version: '3.12'
services:
  Blog:
    build: .
    container_name: blog_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/apps
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}